# https://www.keycloak.org/getting-started/getting-started-docker

version: "3.9"
networks:
  keycloak-db-net:
    driver: bridge
  keycloak-back-net:
    driver: bridge
services:
  mysql:
    image: mysql:8
    networks:
      - keycloak-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Hongkong
      - MYSQL_INITDB_SKIP_TZINFO=true
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    ports:
      - "${EXPOSING_DATABASE}:3306"
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    networks:
      - keycloak-db-net
      - keycloak-back-net
    depends_on:
      - mysql
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Hongkong
    ports:
    - "${EXPOSING_KEYCLOAK}:8080"
    command: ["start","--optimized", "--proxy", "edge", "--hostname-strict","false"]
  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - keycloak
    networks:
      - keycloak-back-net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Hongkong
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
      - "./nginx/ssl:/ssl"
